### ISSUE TITLE
Currently, you can download a single randomized board here.

### ISSUE THREAD

**Issue by akosglue** [rgitzel/azul-generator#2]
link doesn't seem to be working, do you have an update ?

**Comment by rgitzel** [comment]
@akosglue LOL, I've been working the last couple days on getting a proper little site going, with 'dev' and 'prod' so I can tinker without things failing.

I'll fix the link, and have something more stable later today, if work doesn't get in the way.

In the meantime, there's a PDF here if you've not seen it already:  https://boardgamegeek.com/filepage/164845/randomized-azul-board

And, if I may, how did you find this?  :-)

**Comment by akosglue** [comment]
Alright, thanks, now I can see the results.

I was looking for an implementation of the game, because I want to play it online with my brother who lives in an other country. Then I found this repo :-) 
Maybe I will make my own version of it.

Besides, I find this a good idea, to have an other pattern, kinda extending the base game.

**Comment by akosglue** [comment]
The issue is fixed by your update, so I am closing this.
